ENOT-AutoDL/onnx2torch

README.md, setup.py
Here we add a readme file and add some information to the setup.py.
=> Add readme

onnx2torch/node_converters/activations.py, tests/node_converters/activations_test.py
Added 2 new activations:
- HardSigmoid
- LeakyRelu
And sorted order of activations in `activations.py`
=> New activations

onnx2torch/converter.py, onnx2torch/node_converters/nms.py, onnx2torch/onnx_graph.py, tests/node_converters/nms_test.py
Add support of optional arguments.
=> Optional args

onnx2torch/node_converters/__init__.py, onnx2torch/node_converters/logical.py, tests/node_converters/binary_operations_test.py, tests/node_converters/logical_test.py
add logical operations:
- Not
- And
- Or
- Xor
=> add logical operations

README.md, onnx2torch/common.py, onnx2torch/node_converters/expand.py, onnx2torch/node_converters/logical.py, onnx2torch/node_converters/nms.py, onnx2torch/node_converters/reduce.py, onnx2torch/node_converters/scatter_nd.py, onnx2torch/node_converters/squeeze.py, onnx2torch/node_converters/unsqueeze.py
* removed useless context manager (SkipTorchTracing)
* removed useless debug prints
=> removed useless context manager

onnx2torch/node_converters/resize.py
* fixed checking of empty inputs
* fixed conversion of interpolation modes
=> FIX: resize inputs

onnx2torch/converter.py
Fix optional arguments if last arguments are not passed.
=> fix_optional_args

onnx2torch/node_converters/scatter_nd.py, tests/node_converters/scatter_nd_test.py
=> fix scatter nd

onnx2torch/node_converters/scatter_nd.py, tests/node_converters/scatter_nd_test.py
=> fix slow scatternd

onnx2torch/node_converters/constant_of_shape.py, onnx2torch/node_converters/reshape.py, onnx2torch/node_converters/shape.py, onnx2torch/node_converters/slice.py, onnx2torch/node_converters/tile.py, onnx2torch/utils/custom_export_to_onnx.py
fixed export to onnx for
* Reshape
* Shape
* Slice
* Tile
=> Fix: export to onnx

README.md, onnx2torch/node_converters/activations.py, tests/models/models_test.py, tests/node_converters/activations_test.py, tests/utils/resources.py
- Fix models downloading for tests
- Add LogSoftmax
=> Fix: model tests

tests/node_converters/expand_test.py
=> fix expand test for onnx 1.11

onnx2torch/node_converters/reduce.py, onnx2torch/node_converters/squeeze.py, onnx2torch/node_converters/unsqueeze.py
fixed type of axes parameter (squeeze/unsqueeze/reduce)
=> FIX: type of axes parameter (squeeze/unsqueeze/reduce)

onnx2torch/node_converters/conv.py, tests/models/models_test.py, tests/node_converters/conv_test.py, tests/utils/resources.py
Add output_padding for convtranspose
=> Feat convtranspose

onnx2torch/node_converters/gather.py, tests/node_converters/gather_test.py
=> Feat: gather elements

onnx2torch/node_converters/activations.py, onnx2torch/node_converters/pad.py, tests/node_converters/activations_test.py, tests/node_converters/pad_test.py
Add hardswish, celu, elu, selu, softplus, softsign activation
=> feat: add new activations

onnx2torch/node_converters/resize.py
* fixed checking of roi input
* allow to ignore bs+ch dimensions for size input
=> FIX: checking of roi input, allow ignore bs+ch dimensions for size input

onnx2torch/node_converters/activations.py, tests/node_converters/activations_test.py
=> Add PReLU opr

operators.md
=> docs: prelu operators has been supported

onnx2torch/node_converters/clip.py, onnx2torch/node_converters/roialign.py, onnx2torch/utils/common.py, tests/node_converters/slice_test.py, tests/utils/common.py
=> FIX: torch 1.12 errors

onnx2torch/node_converters/activations.py, tests/node_converters/activations_test.py
=> fixed prelu according specs

onnx2torch/utils/safe_shape_inference.py
fixed shape inference of big models
=> FIX: fixed shape inference of big models

onnx2torch/node_converters/average_pool.py, onnx2torch/node_converters/binary_math_operations.py, onnx2torch/node_converters/conv.py, onnx2torch/node_converters/max_pool.py, onnx2torch/node_converters/pad.py, onnx2torch/utils/common.py, onnx2torch/utils/padding.py, tests/node_converters/average_pool_max_pool_test.py, tests/node_converters/conv_test.py, tests/node_converters/pad_test.py
added asymmetric padding for Conv and MaxPool
=> FEATURE: added asymmetric padding for Conv and MaxPool

.github/workflows/stale.yml
https://github.com/marketplace/actions/close-stale-issues
=> chore(ci): autoclosing stale issues and PRs

onnx2torch/node_converters/__init__.py, onnx2torch/node_converters/dropout.py, operators.md, tests/node_converters/dropout_test.py
Based on the implementation in https://github.com/ENOT-AutoDL/onnx2torch/pull/51
Unlike PR #51, I don't use "feature dropout" like nn.Dropout2d or
F.dropout2d, as ONNX does not define them [1].
[1] https://github.com/onnx/onnx/issues/113
=> Add Dropout

.gitignore, onnx2torch/node_converters/__init__.py, onnx2torch/node_converters/lrn.py, operators.md, tests/node_converters/lrn_test.py, tests/utils/common.py
This PR is for the same additions as #96 , but I had to make a new one. I renamed the "main" branch on my fork so that pre-commit `no-commit-to-branch` would pass, but in doing so, it deleted the branch that was associated with the old PR and auto-closed the PR. So, here we are. Phew! I think that's it though?
=> feat: add LRN operator support (attempt 2)

.pylintrc, README.md, onnx2torch/node_converters/activations.py, onnx2torch/node_converters/base_element_wise.py, onnx2torch/node_converters/expand.py, onnx2torch/node_converters/gather.py, onnx2torch/node_converters/global_average_pool.py, onnx2torch/node_converters/logical.py, onnx2torch/node_converters/mean.py, onnx2torch/node_converters/nms.py, onnx2torch/node_converters/reduce.py, onnx2torch/node_converters/reshape.py, onnx2torch/node_converters/roialign.py, onnx2torch/node_converters/scatter_nd.py, onnx2torch/node_converters/shape.py, onnx2torch/node_converters/slice.py, onnx2torch/node_converters/squeeze.py, onnx2torch/node_converters/tile.py, onnx2torch/node_converters/unsqueeze.py, onnx2torch/utils/custom_export_to_onnx.py
fixed custom export (torch 1.13.x)
=> fixed custom export (torch 1.13.x)

onnx2torch/node_converters/gather.py, onnx2torch/utils/indices.py
=> fix: upcast indices to int64

onnx2torch/converter.py
=> fix: lambda not found error during torch.save

onnx2torch/node_converters/__init__.py, onnx2torch/node_converters/instance_norm.py, operators.md, tests/node_converters/instance_norm_test.py
Signed-off-by: Mason Ma <masoner6429@gmail.com>
=> feat: InstanceNormalization

onnx2torch/node_converters/__init__.py, onnx2torch/node_converters/layer_norm.py, operators.md, tests/node_converters/layer_norm_test.py
updated to upstream PR #143 by @JohnMasoner
=> feat: LayerNormalization

onnx2torch/node_converters/__init__.py, onnx2torch/node_converters/depth_to_space.py, operators.md, tests/node_converters/depth_to_space_test.py
https://github.com/ENOT-AutoDL/onnx2torch/pull/168
@sushanthr
=> feat: DepthToSpace

onnx2torch/node_converters/activations.py, onnx2torch/node_converters/constant_of_shape.py, onnx2torch/node_converters/pad.py, tests/node_converters/constant_of_shape_test.py
fixed export to onnx ConstantOfShape in case of bool value attribute
=> fix: export to onnx ConstantOfShape in case of bool value attribute

README.md
=> add `import onnx` in example
